# Check out the opsick API documentation (or the config.h header file)
# to find out what each of these settings do.

[host]
log = false
port = 6677
threads = 2
max_clients = 0
max_header_size = 16384
max_body_size = 16777216
db_file = "opsick.db"

[admin]
max_users = 0
max_user_quota = 16777216
use_index_html = false
key_refresh_interval_hours = 72
user_registration_password = "opsick_registration_password"
argon2_time_cost = 16
argon2_memory_cost_kib = 65536
argon2_parallelism = 2
api_key_algo = 0
api_key_public_hexstr = "FF7A2DC59D1A09E2E7677DD1754A961F6510A43C70DF501DAB0DA068461E25C8"